//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditTrail
    {
        public int logID { get; set; }
        public string columnID { get; set; }
        public string userID { get; set; }
        public string tableName { get; set; }
        public string ipAddress { get; set; }
        public string action { get; set; }
        public string operation { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
    }
}
