//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class barcode
    {
        public string barcode1 { get; set; }
        public string SKU { get; set; }
        public int prodTypeID { get; set; }
        public int prodSubTypeID { get; set; }
        public string itemModelID { get; set; }
        public Nullable<int> chargeID { get; set; }
        public Nullable<int> kitCode { get; set; }
        public long RID { get; set; }
        public Nullable<long> PID { get; set; }
        public Nullable<long> DID { get; set; }
        public string LID { get; set; }
        public Nullable<int> discountID { get; set; }
        public int CPuomID { get; set; }
        public int RPuomID { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<decimal> retailPrice { get; set; }
        public Nullable<decimal> costPrice { get; set; }
        public Nullable<decimal> inventoryCost { get; set; }
        public string posDesc { get; set; }
        public string salesTax { get; set; }
        public string purchaseTax { get; set; }
        public Nullable<bool> isDiscountable { get; set; }
        public Nullable<bool> isActive { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
        public string userID { get; set; }
    }
}
