//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoryHierarchy
    {
        public string RID { get; set; }
        public string code { get; set; }
        public string desc { get; set; }
        public string rType { get; set; }
        public string pDesc { get; set; }
        public Nullable<bool> isActive { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
    }
}
