//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class componentSetup
    {
        public int kitID { get; set; }
        public string code { get; set; }
        public string masterBarcode { get; set; }
        public string prodBarcode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
        public Nullable<int> userID { get; set; }
    }
}
