//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactDIR
    {
        public int contactID { get; set; }
        public string TID { get; set; }
        public int typeID { get; set; }
        public string cDesc { get; set; }
        public Nullable<bool> isPrimary { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
        public string userID { get; set; }
    }
}
