//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoCategory
    {
        public string infoCatID { get; set; }
        public string infoCatDesc { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
    }
}
