//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order
    {
        public string orderNo { get; set; }
        public string poType { get; set; }
        public string modID { get; set; }
        public string poolID { get; set; }
        public string delAddressID { get; set; }
        public Nullable<int> discountID { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public Nullable<System.DateTime> cancelDate { get; set; }
        public string salesTax { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
        public string userID { get; set; }
    }
}
