//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class receiving
    {
        public string rrNum { get; set; }
        public string orderNo { get; set; }
        public string invoice { get; set; }
        public string ACRnum { get; set; }
        public string voyageNum { get; set; }
        public string vanNum { get; set; }
        public string cartons { get; set; }
        public Nullable<System.DateTime> dateArrived { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
    }
}
