//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tbl
    {
        public int userID { get; set; }
        public string authID { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string RID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
    }
}
