//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCatHierarchyTree
    {
        public string div_rid { get; set; }
        public string div_code { get; set; }
        public string div_desc { get; set; }
        public string div_rType { get; set; }
        public string dept_RID { get; set; }
        public string dept_code { get; set; }
        public string dept_desc { get; set; }
        public string dept_rType { get; set; }
        public string cat_RID { get; set; }
        public string cat_code { get; set; }
        public string cat_desc { get; set; }
        public string cat_rType { get; set; }
        public string subcat_RID { get; set; }
        public string subcat_code { get; set; }
        public string subcat_desc { get; set; }
        public string subcat_rType { get; set; }
    }
}
