//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwItemModelGroup
    {
        public string itemModelID { get; set; }
        public string sdGroupID { get; set; }
        public string sdGroupDesc { get; set; }
        public string itemModelDesc { get; set; }
    }
}
