//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwItemSalesTaxSetup
    {
        public string itemTaxID { get; set; }
        public string TaxDesc { get; set; }
        public int SID { get; set; }
        public string name { get; set; }
        public Nullable<decimal> percent { get; set; }
    }
}
