//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwKitComponent
    {
        public int kitID { get; set; }
        public string code { get; set; }
        public string masterBarcode { get; set; }
        public string prodBarcode { get; set; }
        public string posDesc { get; set; }
        public Nullable<decimal> qty { get; set; }
        public int RPuomID { get; set; }
        public string uomDesc { get; set; }
    }
}
