//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLineDiscount
    {
        public int discountID { get; set; }
        public string suppID { get; set; }
        public string name { get; set; }
        public string dDesc { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
    }
}
