//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOtherPrice
    {
        public string SKU { get; set; }
        public string barcode { get; set; }
        public int priceID { get; set; }
        public string priceDesc { get; set; }
        public Nullable<decimal> priceAmt { get; set; }
    }
}
