//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPO_Line
    {
        public string orderNo { get; set; }
        public string SKU { get; set; }
        public string barcode { get; set; }
        public string posDesc { get; set; }
        public string subcat_code { get; set; }
        public string subcat_desc { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> rcve { get; set; }
        public string CPuomDesc { get; set; }
        public Nullable<decimal> costPrice { get; set; }
        public Nullable<decimal> retailPrice { get; set; }
        public string lineDisc { get; set; }
        public Nullable<decimal> Net_amount { get; set; }
        public string remarks { get; set; }
    }
}
