//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPOReport
    {
        public string orderNo { get; set; }
        public string SKU { get; set; }
        public string barcode { get; set; }
        public string suppID { get; set; }
        public string name { get; set; }
        public string agent { get; set; }
        public string payDesc { get; set; }
        public string poolDesc { get; set; }
        public string RID { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public Nullable<System.DateTime> cancelDate { get; set; }
        public string Address { get; set; }
        public string posDesc { get; set; }
        public string lineDisc { get; set; }
        public Nullable<int> qty { get; set; }
        public string uomDesc { get; set; }
        public Nullable<decimal> costPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
