//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProductList
    {
        public string SKU { get; set; }
        public string itemDesc { get; set; }
        public string prodTypeDesc { get; set; }
        public string prodSubTypeDesc { get; set; }
        public string pDimension { get; set; }
        public string desc { get; set; }
        public Nullable<bool> isConcession { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
    }
}
