//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProdPurchasing
    {
        public int pPurchasingID { get; set; }
        public Nullable<decimal> costPrice { get; set; }
        public string uomID { get; set; }
        public string uomDesc { get; set; }
    }
}
