//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProductCost
    {
        public string barcode { get; set; }
        public int CPuomID { get; set; }
        public string CPuomDesc { get; set; }
        public Nullable<decimal> costPrice { get; set; }
    }
}
