//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProduct
    {
        public string Barcode { get; set; }
        public string SKU { get; set; }
        public string brandID { get; set; }
        public string Product_description { get; set; }
        public int CPuomID { get; set; }
        public string PO_Unit { get; set; }
        public Nullable<decimal> Cost_price { get; set; }
        public Nullable<decimal> factor { get; set; }
        public int RPuomID { get; set; }
        public Nullable<decimal> Retail_price { get; set; }
        public string bDesc { get; set; }
        public int prodTypeID { get; set; }
        public string Retail_Unit { get; set; }
        public int prodSubTypeID { get; set; }
        public long RID { get; set; }
        public Nullable<decimal> inventoryCost { get; set; }
        public string purchaseTax { get; set; }
        public string salesTax { get; set; }
        public Nullable<long> DID { get; set; }
        public string BMRX { get; set; }
        public Nullable<long> PID { get; set; }
        public string Privilege_setup { get; set; }
        public string itemModelID { get; set; }
        public string itemModelDesc { get; set; }
        public Nullable<bool> isDiscountable { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> chargeID { get; set; }
        public string chargeDesc { get; set; }
        public Nullable<decimal> percentNum { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
        public string suppID { get; set; }
        public string itemDesc { get; set; }
        public Nullable<bool> isConcession { get; set; }
        public string Product_type { get; set; }
        public string prodSubTypeDesc { get; set; }
        public Nullable<System.DateTime> Date_created { get; set; }
        public string code { get; set; }
        public string desc { get; set; }
        public string rType { get; set; }
        public string pDesc { get; set; }
        public string pDimension { get; set; }
        public Nullable<int> kitCode { get; set; }
        public string LID { get; set; }
        public string Location { get; set; }
        public string whID { get; set; }
        public string whDesc { get; set; }
        public string siteID { get; set; }
        public Nullable<int> discountID { get; set; }
        public string dDesc { get; set; }
    }
}
