//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPurchaseOrder
    {
        public string Department { get; set; }
        public string Order_No { get; set; }
        public string poType { get; set; }
        public string Supplier_ID { get; set; }
        public string Name { get; set; }
        public string agent { get; set; }
        public string payDesc { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date_created { get; set; }
        public Nullable<System.DateTime> Delivery_date { get; set; }
        public Nullable<System.DateTime> Cancellation_date { get; set; }
        public string Pool_ID { get; set; }
        public string Pool_name { get; set; }
        public string Status { get; set; }
        public string delAddressID { get; set; }
        public string desc { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string modDesc { get; set; }
        public string remarks { get; set; }
        public string delRemarks { get; set; }
        public Nullable<bool> isConcession { get; set; }
    }
}
