//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSite
    {
        public string siteID { get; set; }
        public string siteDesc { get; set; }
        public Nullable<int> addressID { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string province { get; set; }
    }
}
