//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSupplier
    {
        public string table_name { get; set; }
        public string Supplier_ID { get; set; }
        public string itemTaxID { get; set; }
        public string TaxDesc { get; set; }
        public string Name { get; set; }
        public string Agent { get; set; }
        public Nullable<bool> isDistributor { get; set; }
        public string Record_type { get; set; }
        public string Group { get; set; }
        public string Payment_term { get; set; }
        public Nullable<System.DateTime> Date_created { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string RID { get; set; }
    }
}
