//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwWarehouseSetup
    {
        public string LID { get; set; }
        public string desc { get; set; }
        public string whID { get; set; }
        public string whDesc { get; set; }
        public string siteID { get; set; }
        public string siteDesc { get; set; }
    }
}
